### ISSUE TITLE
Benchmark Insert 100% 

### ISSUE THREAD

**Issue by eric-haibin-lin** [EccentricLoggers/peloton#53]
Vacuum GC. **No Logging is performing worse than Async Logging.** (Why?)

**Comment by eric-haibin-lin** [comment]
<img width="528" alt="screen shot 2016-04-30 at 11 45 27 am" src="https://cloud.githubusercontent.com/assets/5545640/14937034/1aaa9478-0ec9-11e6-8eb1-bdbb06bb689f.png">

**Comment by eric-haibin-lin** [comment]
<img width="498" alt="screen shot 2016-04-30 at 3 35 45 pm" src="https://cloud.githubusercontent.com/assets/5545640/14938165/5c3aec38-0ee9-11e6-9187-c0a0209ccc12.png">

**Comment by MattPerron** [comment]
How many backends is this?

**Comment by MattPerron** [comment]
Also, for setting the flush frequency, the parameter you are passing in is the number on the x-axis \* 1000 right?

**Comment by eric-haibin-lin** [comment]
@MattPerron  See the number of backend in the title of each figure. 
Ah, I didn't notice it's microsec, I'll re-run it.

**Comment by MattPerron** [comment]
@eric-haibin-lin Since we are using SSDs I think the appropriate flush time is probably 10s-100s of microseconds. Also, for synchronous we should be running with more backends or we won't see any performance improvement.

**Comment by MattPerron** [comment]
@eric-haibin-lin My best guess for why logging throughput is higher with logging enabled is that it is somehow reducing contention on a trashing lock (because it is calling our code)

**Comment by eric-haibin-lin** [comment]
<img width="632" alt="screen shot 2016-04-30 at 5 15 31 pm" src="https://cloud.githubusercontent.com/assets/5545640/14938614/34941d2c-0ef7-11e6-9229-525ac3eb4dc7.png">

**Comment by abhishekjoshi2** [comment]
![image](https://cloud.githubusercontent.com/assets/7502799/14940553/96c004e2-0f48-11e6-8aeb-48f569669617.png)

**Comment by abhishekjoshi2** [comment]
This image is from benchmarking multiple loggers, and since has a lot of stuff, I'll summarize what I saw during these tests (all these values are for the value of "u" as 1.0, I'm not sure if that is Updates or Inserts):
- Increasing the number of loggers helps in the asynchronous logging case, because we can be I/O-bandwidth bound here
- Increasing the number of loggers does not help in the synchronous logging case, because we are not bandwidth bound there (the lines for 1, 2 and 3 loggers completely overlap each other)
- For the single logger, async case, I did not observe better performance than the no logging case (contrary to what Eric saw), but for multiple loggers, logging had better performance than no logging

<img width="903" alt="screen shot 2016-05-01 at 3 15 20 am" src="https://cloud.githubusercontent.com/assets/7502799/14940606/fa5568ce-0f4a-11e6-8a30-dd6cd4e410fc.png">

**Comment by abhishekjoshi2** [comment]
100% inserts
Scale factor = 1
Old ycsb
10 seconds

<img width="620" alt="screen shot 2016-05-04 at 5 50 16 am" src="https://cloud.githubusercontent.com/assets/7502799/15010800/1bad1954-11bc-11e6-9186-3207daf7aa12.png">
